sudo: true
dist: "trusty"
language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip3 install termcolor
  - pip3 install coala-bears

script:
  - coala --files *.py --bears PEP8Bear,PyUnusedCodeBear,SpaceConsistencyBear
